### ISSUE TITLE
Request review

### ISSUE THREAD

**Issue by miyconst** [miyconst/StarcounterRazor#1]
@warpech, @alemoi, @andwah, @chrhol, @per-samuelsson, @dan31

I have finished the Razor views in Starcounter demo project.
Could you please find a couple of minutes to take a look?

### Introduction

[Razor](http://www.w3schools.com/aspnet/razor_intro.asp) is a c# markup language which is simpler than PHP. ASP.NET uses Razor to generate views. Razor could also be used to generate rich email templates, xml documents, text documents in any .Net application, including Console and Windows Applications.

Using Razor as a template markup engine does not disable Polymer template binding, as those two intend to serve different roles in the web application.

#### Server side Layout pages

Right now we have to include those lines into each partial:

```html
<template>
    <template is="dom-bind" id="root">
        <!-- HTML goes here -->
        <dom-bind-notifier observed-object="{{model}}" path="model" deep></dom-bind-notifier>
    </template>
</template>
```

It is not that much of code, but it is still 5 lines of code copy-pasted across all of the partial views. Also, every now and then I got asked by our customers why something is not working, and it ends up to be some misspelling in `dom-bind-notifier` declaration.

With Razor we can define a Layout page, and it will look like this:

##### Layout.cshtml

```html
<template>
    <template is="dom-bind" id="root">
        @RenderBody()
        <dom-bind-notifier observed-object="{{model}}" path="model" deep></dom-bind-notifier>
    </template>
</template>
```

##### Partial.cshtml

```html
@{
    Layout = "Layout.cshtml";
}
<p>I don't have to care about template and dom-bind-notifier any more!</p>
```

#### One view to serve multiple user roles

If an application, for example Warehouse, has many user roles with a small unique feature, then it is impossible to create separate HTML view file for every possible role combination.

On other hand, it is not correct to include all of that html inside `<template is="dom-if">` on the page, if the end user does not have rights to access this part of the HTML.

Here Razor comes to rescue. We can add `@if (user.Role == MyCustomRole) { }` and those chunks of code will be resolved on server side. The client will never see the protected content and we still have a single view file.

#### Search engine optimization

Polymer binding is terrible for search engines optimization. I know, we can setup a NodeJs module on top of that and response with pure HTML to search engines, but this is a huge work compare to using Razor in the places where it is needed.

#### Email letters generation

And of course we can use Razor to generate email documents.

**Comment by miyconst** [comment]
Just finished a long discussion with @Starcounter-Jack, and it looks like Razor might get a chance to live in Starcounter.

This is not urgent, but once again requesting review from: @warpech, @alemoi, @andwah, @chrhol, @per-samuelsson, @dan31.

**Comment by dan31** [comment]
@miyconst thank you for a useful into! I have a question in the light of performance. How frequently the engine is to be invoked while in production use? I consider templating engines, being used on the server side, are known to consume cpu cycles and difficult in caching, since the html is dynamically produced. Hence with server-side generated html's it is less likely to use CDNs and other optimised means for static content delivery. Meaning more load onto the backend and greater consumption of the bandwidth. The bandwidth is not to be an issue unless you own a cloud catering for 1000s of users. What is your argument about these viewpoints?

**Comment by per-samuelsson** [comment]
@miyconst 

Sorry, I never saw this until now. Interesting thing you've got going there! I will really try to find some time reading it carefully and considering it some more, and then give you feedback.

**Comment by miyconst** [comment]
>I have a question in the light of performance.

This is not **a** question, it is **the** question. 

Generating a Razor view can be an expensive task, but not always. The view itself is compiled and saved in memory like a c# method. So, in the end it costs same as a plain c# method to generate HTML.

>How frequently the engine is to be invoked while in production use?

This can/should be configured. 

- Views without data and view-model dependencies - **cached forever**.
- Views with signed in user dependency - **cached per session**.
- Views with data and/or view-model dependencies - **smartly cached or not cached at all**.

**Smartly cached** - the caching mechanism should check whether dependent data items been changed since the time cache was created.

**Not cached at all** - such views will trigger Razor engine every time user requests page.

The good thing is that generating views can be "scaled out" to another server.

**Comment by miyconst** [comment]
>Sorry, I never saw this until now. Interesting thing you've got going there! I will really try to find some time reading it carefully and considering it some more, and then give you feedback.

No problem, this is not something we need yesterday.

**Comment by jwillmer** [comment]
> No problem, this is not something we need yesterday.

But maybe tomorrow?

**Comment by dan31** [comment]
I like your style guys :)
I believe it is possible to get this done right on our side. Inefficiency cannot be excused (last time I ever touched asp.net I got impression that overall sluggishness came from the server-side generated pages, maybe I just didn't know how to cook it efficiently), yet done properly that is a powerful tool. Let's engage more people into the review.

**Comment by per-samuelsson** [comment]
I have now tried to read in on this topic a bit. It's certainly not an area I feel very confident in.

I really don't have anything about Razor. In fact, I actually like the approach to mix C# and HTML and I find those pages really intuitive. Actually, more appealing than what I've seen in Polymer.

Still, I'm having problem to see what we actually solve by introducing Razor into our mix. Is it "just" to replace those 5 boilerplate lines of HTML, or do we get more? (Generating XML and/or emails don't really seem to me as something we need to improve on).

To make it more clear, could you provide a simple "triplet" (pseudo-code is fine), one like it would look today, and one where we utilize Razor as you propose. Does it become a "fourlet"?

Final disclaimer: if the level I'm at in this area is to low for you guys, I'm fine if you just ignore my concerns and go ahead with what you think is best. Again, I'm really novice here. :smile:

**Comment by jwillmer** [comment]
The main benefit I see is that you can exclude html parts server side. That means that not authorized persons can not see the page structure of authorized persons in the html.

Another thing where I would use razor is maybe for calculating `readonly` property's on the page. Because they may not be interesting in the view model.

**Comment by per-samuelsson** [comment]
> Another thing where I would use razor is maybe for calculating `readonly` property's on the page. Because they may not be interesting in the view model.

How would such thing work? Could you elaborate a bit on that, as I haven't heard that argument before.

**Comment by per-samuelsson** [comment]
> I really don't have anything about Razor. In fact, I actually like the approach to mix C# and HTML and I find those pages really intuitive. Actually, more appealing than what I've seen in Polymer.

Just a small addition to this statement I wrote last night: introducing Razor also means we **add** one extra concept our users need to understand, making the product more complex (even though I suspect a lot of our users will already be familiar with it). We introduce a new syntax, and a new file format (`.cshtml`). The benefits gained should justice that. Do they?

**Comment by jwillmer** [comment]
> How would such thing work? Could you elaborate a bit on that, as I haven't heard that argument before.

For example I like to display the user some average:
`<span>@string.Format("{0:c}", (model.workhours/365))</span>`

**Comment by miyconst** [comment]
>We introduce a new syntax, and a new file format (.cshtml). The benefits gained should justice that. Do they?

This is not something required for an app to work, but something we "also support". So, it won't be like "you have to learn", but rather "if you would like to use, then read how to".

**Comment by warpech** [comment]
Sorry for coming late to the review!

As for the regular web apps, I would like to not break away from our vision of client-side rendered views with two-way data binding. That's our distinctive feature that boosts up the development, and we need to focus on improving that.

BUT I think Razor it is a great solution for generating static HTML reports, etc. Where a noninteractive HTML is the desired result. And we really need one like that in our tool belt, because Puppet does not allow that. @miyconst is this the usage you have in mind as well?

1. `cshtml` should not be in `wwwroot` because they are not static files
2. I followed the instructions in README, but still cannot run the program. I get the following exception: 

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Can not find file in Page->Html property: ""/StarcounterRazor/Temp/526387EC5863042A00000010/635937208783544110-IndexPage.html""
   at Starcounter.Page.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in C:\BuildAgent\work\sc-develop-nightly-218\Level1\src\Starcounter\Page.cs:line 54
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\BuildAgent\work\sc-develop-nightly-218\Level1\src\Starcounter.Internal\Http\Response.cs:line 809
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\BuildAgent\work\sc-develop-nightly-218\Level1\src\Starcounter.Internal\Http\Request.cs:line 1224
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\BuildAgent\work\sc-develop-nightly-218\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 605
ParamName=Can not find file in Page->Html property: ""/StarcounterRazor/Temp/526387EC5863042A00000010/635937208783544110-IndexPage.html""
HResult=-2146233086
```

**Comment by miyconst** [comment]
>@miyconst is this the usage you have in mind as well?

Yes and no. It could be used to generate print version of a page, but also can be used to render some `dynamic per user`, but `static per session` sections.

For example admin has rights to edit any field, manager does not have access to password field. Currently we have to send `HasAccessToPassword` value to the client and apply a binding.

```html
<input type="text" disabled$="{{!model.HasAccessToPassword}}" />
```

It would be much easier to just do the following:

```html
<input type="text" @(currentUser.IsManager ? "disabled" : null) />
```

More elegant solution:

```html
@if (currentUser.IsManager) {
    <input type="text" disabled />
} else {
   <input type="text" />
}
```

So this also moves in the direction of keeping the client thin and the server thick.

**Comment by miyconst** [comment]
>cshtml should not be in wwwroot because they are not static files.

Agree. I also thought about it. The files may contain sensitive information and should not be available for download.

>I get the following exception

For me it looks like you didn't set up properly working directory.

**Comment by warpech** [comment]
> Yes and no. It could be used to generate print version of a page, but also can be used to render some dynamic per user, but static per session sections.

I get the point, but I have a feeling that mixing two templating languages in the same file will drive us crazy. If possible, you can just use different `.html` Polymer templates for different user roles.

> For me it looks like you didn't set up properly working directory.

My working directory is: `C:\www\miyconst\StarcounterRazor\StarcounterRazor\wwwroot\`. But I can tell that the template files are being created in `C:\www\miyconst\StarcounterRazor\StarcounterRazor\StarcounterRazor\Temp` (notice 3x `StarcoutnerRazor`). Is my config still wrong or something wrong with the program? Are you launching from VS or CLI?

**Comment by miyconst** [comment]
>I get the point, but I have a feeling that mixing two templating languages in the same file will drive us crazy.

Some might get crazy. For me this is a daily thing I get used to so much, end enjoyed it.

>If possible, you can just use different .html Polymer templates for different user roles.

And this would really drive me crazy when I have "kind of same" page for five different roles.

>My working directory is: `C:\www\miyconst\StarcounterRazor\StarcounterRazor\wwwroot\`.

The working directory should point to the resource directory, so this seems to be right. I run from VS.

**Comment by miyconst** [comment]
Closing the issue as too old.
